server:
  port: 8001

spring:
  application:
    name: cloudpayment

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver #org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.21.129:3306/cloudpayment?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.future.springcloud.entities